In [1]:
import pandas as pd

base = r"C:\Users\bisar\Downloads\hearthwell_data_kit"

print(open(base + r"\reviews\reviews_2026-09-02.json", encoding="utf-8").read()[:400])

reviews = pd.read_json(base + r"\reviews\reviews_2026-09-02.json")
tickets = pd.read_csv(base + r"\tickets\tickets_2026-09-07.csv")

print(reviews.shape, tickets.shape)
print(reviews.dtypes)
print(tickets.dtypes)
reviews.head()

[{"review_id": "R-000896", "product_id": "P030", "customer_id": "C00208", "rating": 3, "title": "Decent but flawed", "body": "Arrived two days early, very fast shipping. But the manual was missing pages.", "created_at": "2026-09-02T01:36:22Z", "verified_purchase": true, "helpful_votes": 0}, {"review_id": "R-000753", "product_id": "P040", "customer_id": "C01731", "rating": 5, "title": "Exactly what
(368, 9) (527, 8)
review_id                         object
product_id                        object
customer_id                       object
rating                             int64
title                             object
body                              object
created_at           datetime64[ns, UTC]
verified_purchase                   bool
helpful_votes                      int64
dtype: object
ticket_id         object
created_date      object
product_id        object
customer_email    object
subject           object
description       object
status            object
channel           object
dtype: object

,review_id,product_id,customer_id,rating,title,body,created_at,verified_purchase,helpful_votes
0,R-000896,P030,C00208,3,Decent but flawed,"Arrived two days early, very fast shipping. Bu...",2026-09-02 01:36:22+00:00,True,0
1,R-000753,P040,C01731,5,Exactly what I needed,"The dial fits snugly, no wobble.",2026-09-02 16:39:34+00:00,True,0
2,R-001035,P033,C00127,4,Five stars,<p>Surprisingly quiet.</p>,2026-09-02 15:14:59+00:00,True,0
3,R-000962,P035,C02476,3,Mixed feelings,"Support replaced it in two days, great service...",2026-09-02 21:40:41+00:00,True,1
4,R-001066,P012,C02611,2,Do not buy,"<div>Just what I wanted, a kettle that leaks a...",2026-09-02 18:38:54+00:00,True,1

In [3]:
tickets.head()

,ticket_id,created_date,product_id,customer_email,subject,description,status,channel
0,T-000512,2026-09-10,P023,olivia.smith9754@mailbox.example,Return request,"Hey, I bought the Hearthwell Elite Container S...",closed,chat
1,T-000732,11-Sep-2026,P047,noah.miller2529@mailbox.example,Not working,"Hi, I bought the Hearthwell Elite Towel Set (o...",closed,chat
2,T-000596,09/11/2026,P001,omar.moore8235@mailbox.example,Return request,"Hi, I bought the Hearthwell Classic Blender (o...",closed,email
3,T-000656,12-Sep-2026,P004,noah.miller7205@mailbox.example,Return request,"Hello team, I bought the Hearthwell Max Blende...",open,email
4,T-000539,09/13/2026,P020,maria.davis9294@mailbox.example,Need help,"Hey, I bought the Hearthwell Pro Container Set...",open,email

In [2]:
print(reviews.isna().sum())
print(tickets.isna().sum())
print(tickets["created_date"].sample(8, random_state=1).tolist())
print(tickets["description"].iloc[0])

review_id             0
product_id            0
customer_id          16
rating                0
title                 0
body                  0
created_at            0
verified_purchase     0
helpful_votes         0
dtype: int64
ticket_id          0
created_date       0
product_id        25
customer_email     0
subject            0
description        0
status             0
channel            0
dtype: int64
['2026-09-12', '2026-09-10', '2026-09-07', '2026-09-11', '2026-09-12', '09/09/2026', '09/13/2026', '2026-09-13']
Hey, I bought the Hearthwell Elite Container Set (order #678274). The lid doesn't fit properly. This is the second time this has happened.

On Sep 10, 2026 Support <help@hearthwell.example> wrote:
> Hello, thanks for contacting Hearthwell. How can we help?

In [5]:
import glob, os, json
import pandas as pd

base = r"C:\Users\bisar\Downloads\hearthwell_data_kit"

frames = []
for f in sorted(glob.glob(base + r"\reviews\*.json")):
    with open(f, encoding="utf-8") as fh:
        df = pd.DataFrame(json.load(fh))
    df["source_file"] = os.path.basename(f)
    frames.append(df)
reviews = pd.concat(frames, ignore_index=True)

frames = []
for f in sorted(glob.glob(base + r"\tickets\*.csv")):
    df = pd.read_csv(f, dtype=str)
    df["source_file"] = os.path.basename(f)
    frames.append(df)
tickets = pd.concat(frames, ignore_index=True)

products = pd.read_csv(base + r"\products.csv", dtype=str)
customers = pd.read_csv(base + r"\customers.csv", dtype=str)

In [8]:
reviews.shape

(25396, 10)

In [7]:
tickets.shape

(4277, 9)

In [9]:
reviews["source_file"].nunique()

56

In [10]:
tickets["source_file"].nunique()

8

In [12]:
print(reviews.shape, tickets.shape)
print(reviews.groupby("source_file").size().describe())
print(tickets.groupby("source_file").size())

(25396, 10) (4277, 9)
count     56.000000
mean     453.500000
std       65.628708
min      346.000000
25%      404.750000
50%      453.000000
75%      496.000000
max      614.000000
dtype: float64
source_file
tickets_2026-08-31.csv    512
tickets_2026-09-07.csv    527
tickets_2026-09-14.csv    478
tickets_2026-09-21.csv    602
tickets_2026-09-28.csv    508
tickets_2026-10-05.csv    502
tickets_2026-10-12.csv    595
tickets_2026-10-19.csv    553
dtype: int64

In [13]:
# ---- Q1: how big is the data, and is any file different? ----
print("Reviews:", len(reviews), "rows | Tickets:", len(tickets), "rows")
print("\nRows per review file:")
print(reviews.groupby("source_file").size().describe())
print("\nRows per ticket file:")
print(tickets.groupby("source_file").size())

print("\nFirst 3 column names of each ticket file:")
for f in sorted(glob.glob(base + r"\tickets\*.csv")):
    print(os.path.basename(f), list(pd.read_csv(f, nrows=0).columns)[:3])

print("\nTypes found in the rating column:")
print(reviews["rating"].map(type).value_counts())
print("Files where rating is text:", reviews[reviews["rating"].map(type) == str]["source_file"].unique())

# ---- Q2: duplicates ----
n = len(reviews)
dup_id  = reviews["review_id"].duplicated().sum()
dup_row = reviews.drop(columns="source_file").duplicated().sum()
print(f"\nReviews: repeated review_id = {dup_id} ({dup_id/n*100:.1f}%) | fully identical rows = {dup_row}")

t = len(tickets)
tdup_id  = tickets["ticket_id"].duplicated().sum()
tdup_row = tickets.drop(columns="source_file").duplicated().sum()
print(f"Tickets: repeated ticket_id = {tdup_id} ({tdup_id/t*100:.1f}%) | fully identical rows = {tdup_row}")

# ---- Q3: missing values ----
print("\nReviews, % missing per column:")
print((reviews.isna().sum() / len(reviews) * 100).round(1))
print("\nTickets, % missing per column:")
print((tickets.isna().sum() / len(tickets) * 100).round(1))
print("\nReviews with an empty title:", (reviews["title"] == "").sum())

Reviews: 25396 rows | Tickets: 4277 rows

Rows per review file:
count     56.000000
mean     453.500000
std       65.628708
min      346.000000
25%      404.750000
50%      453.000000
75%      496.000000
max      614.000000
dtype: float64

Rows per ticket file:
source_file
tickets_2026-08-31.csv    512
tickets_2026-09-07.csv    527
tickets_2026-09-14.csv    478
tickets_2026-09-21.csv    602
tickets_2026-09-28.csv    508
tickets_2026-10-05.csv    502
tickets_2026-10-12.csv    595
tickets_2026-10-19.csv    553
dtype: int64

First 3 column names of each ticket file:
tickets_2026-08-31.csv ['ticket_id', 'created_date', 'product_id']
tickets_2026-09-07.csv ['ticket_id', 'created_date', 'product_id']
tickets_2026-09-14.csv ['ticket_id', 'created_date', 'product_id']
tickets_2026-09-21.csv ['ticket_id', 'created_date', 'product_id']
tickets_2026-09-28.csv ['ticket_id', 'created_date', 'product_id']
tickets_2026-10-05.csv ['created_date', 'ticket_id', 'customer_email']
tickets_2026-10-12.csv ['ticket_id', 'created_date', 'product_id']
tickets_2026-10-19.csv ['ticket_id', 'created_date', 'product_id']

Types found in the rating column:
rating
<class 'int'>    24939
<class 'str'>      457
Name: count, dtype: int64
Files where rating is text: ['reviews_2026-09-24.json']

Reviews: repeated review_id = 2248 (8.9%) | fully identical rows = 2167
Tickets: repeated ticket_id = 120 (2.8%) | fully identical rows = 120

Reviews, % missing per column:
review_id            0.0
product_id           0.0
customer_id          3.1
rating               0.0
title                0.0
body                 0.0
created_at           0.0
verified_purchase    0.0
helpful_votes        0.0
source_file          0.0
dtype: float64

Tickets, % missing per column:
ticket_id         0.0
created_date      0.0
product_id        5.7
customer_email    0.0
subject           0.0
description       0.0
status            0.0
channel           0.0
source_file       0.0
dtype: float64

Reviews with an empty title: 4918

In [14]:
# ---- Q4: dates ----
shape = (tickets["created_date"]
         .str.replace(r"\d", "d", regex=True)
         .str.replace(r"[A-Za-z]", "a", regex=True))
print("Ticket date formats (d = digit, a = letter):")
print(shape.value_counts())

slash = tickets[tickets["created_date"].str.contains("/")]["created_date"]
first  = slash.str.split("/").str[0].astype(int)
second = slash.str.split("/").str[1].astype(int)
print("\nSlash dates:", len(slash), "| first number > 12:", (first > 12).sum(), "| second number > 12:", (second > 12).sum())

ts = pd.to_datetime(reviews["created_at"], utc=True)
print("\nReview dates run from", ts.min(), "to", ts.max())

# ---- Q5: text problems ----
html_n = reviews["body"].str.contains(r"<[^>]+>|&\w+;", regex=True).sum()
print(f"\nReviews with HTML: {html_n} ({html_n/len(reviews)*100:.1f}%)")
for label, pat in [("quoted reply ('wrote:')", "wrote:"),
                   ("'Sent from my iPhone'", "Sent from my iPhone"),
                   ("confidentiality notice", "CONFIDENTIALITY NOTICE"),
                   ("'Regards,' sign-off", "Regards,")]:
    c = tickets["description"].str.contains(pat, regex=False).sum()
    print(f"Tickets with {label}: {c} ({c/len(tickets)*100:.1f}%)")

short = reviews["body"].str.len() < 10
print("\nReviews with body under 10 characters:", short.sum())
print(reviews[short]["body"].value_counts().head(10))

# ---- Q6: broken links ----
print("\nReview product_ids not in products:", (~reviews["product_id"].dropna().isin(products["product_id"])).sum())
print("Ticket product_ids not in products:", (~tickets["product_id"].dropna().isin(products["product_id"])).sum())
print("Ticket emails not in customers:", (~tickets["customer_email"].isin(customers["email"])).sum())

Ticket date formats (d = digit, a = letter):
created_date
aa/aa/aaaa     1444
aaaa-aa-aa     1424
aa-aaa-aaaa    1409
Name: count, dtype: int64

Slash dates: 1444 | first number > 12: 0 | second number > 12: 857

Review dates run from 2026-08-31 00:03:03+00:00 to 2026-10-25 23:59:18+00:00

Reviews with HTML: 1668 (6.6%)
Tickets with quoted reply ('wrote:'): 812 (19.0%)
Tickets with 'Sent from my iPhone': 871 (20.4%)
Tickets with confidentiality notice: 865 (20.2%)
Tickets with 'Regards,' sign-off: 849 (19.9%)

Reviews with body under 10 characters: 1172
body
Love it!!    161
good         154
fine         150
ok           148
meh          144
Nice         141
👍            140
ok ok        127
<p>ok</p>      6
<p>👍</p>       1
Name: count, dtype: int64

Review product_ids not in products: 0
Ticket product_ids not in products: 0
Ticket emails not in customers: 203

In [15]:
dups = reviews[reviews["review_id"].duplicated(keep=False)].copy()
as_text = dups.drop(columns="source_file").astype(str).drop_duplicates()
still_different = as_text[as_text["review_id"].duplicated(keep=False)]
print("IDs whose copies still differ when everything is compared as text:", still_different["review_id"].nunique())

if still_different["review_id"].nunique() > 0:
    print(dups[dups["review_id"] == still_different["review_id"].iloc[0]].T)

IDs whose copies still differ when everything is compared as text: 0

In [16]:
shape = (tickets["created_date"]
         .str.replace(r"[A-Za-z]", "a", regex=True)
         .str.replace(r"\d", "d", regex=True))
print(shape.value_counts())
for s in shape.unique():
    print(s, "->", tickets[shape == s]["created_date"].iloc[0])

created_date
dd/dd/dddd     1444
dddd-dd-dd     1424
dd-aaa-dddd    1409
Name: count, dtype: int64
dd-aaa-dddd -> 02-Sep-2026
dd/dd/dddd -> 09/05/2026
dddd-dd-dd -> 2026-09-01